language: cpp
sudo: required
dist: trusty
env:
  global:
    - secure: "hgyLdDIpm+TpAi7K6n4gHoe5YzOKAj740Ts5DjAhFSa6ayyrm7LXibjkSN+iINBMHwAirLN7C3Ex+JVQK8bguKe0IdiSjDU+SXZ+JtsXNqmV9fOKc3XVjQwI4kRD0Q3/F1mst8fVbeyPQFzETGzlUCp1ofy5rteZIehKsaaoeL0="
addons:
  coverity_scan:
    project:
      name: "AMDmi3/libSDL2pp"
      description: "C++11 bindings/wrapper for SDL2"
    notification_email: amdmi3@amdmi3.ru
    build_command_prepend: "cmake ."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

script:
  - cmake .
  - make
